/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-builder/index.ts to modify the generation of this file.


import { ComponentBuilder } from '@sitecore-jss/sitecore-jss-nextjs';


import * as CallToActionPanel from 'src/components/CallToActionPanel';
import * as ContentBlock from 'src/components/ContentBlock';
import * as Header from 'src/components/Header';
import * as HeroSection from 'src/components/HeroSection';
import * as Highlights from 'src/components/Highlights';
import * as MediaCarousel from 'src/components/MediaCarousel';
import * as TwoColumnLayout from 'src/components/TwoColumnLayout';

export const components = new Map();

components.set('CallToActionPanel', CallToActionPanel);
components.set('ContentBlock', ContentBlock);
components.set('Header', Header);
components.set('HeroSection', HeroSection);
components.set('Highlights', Highlights);
components.set('MediaCarousel', MediaCarousel);
components.set('TwoColumnLayout', TwoColumnLayout);

export const componentBuilder = new ComponentBuilder({ components });

export const moduleFactory = componentBuilder.getModuleFactory();
