/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.ts to modify the generation of this file.
const config = {};
config.sitecoreApiKey = process.env.SITECORE_API_KEY || '{8E540CBF-6FC6-4447-91C1-6595DAD03A77}';
config.sitecoreApiHost = process.env.SITECORE_API_HOST || 'https://gogreensc.dev.local';
config.sitecoreSiteName = process.env.SITECORE_SITE_NAME || 'gogreen';
config.graphQLEndpointPath = process.env.GRAPH_QL_ENDPOINT_PATH || '/sitecore/api/graph/edge';
config.defaultLanguage = process.env.DEFAULT_LANGUAGE || 'en';
config.graphQLEndpoint = process.env.GRAPH_QL_ENDPOINT || 'https://gogreensc.dev.local/sitecore/api/graph/edge';
config.layoutServiceConfigurationName = process.env.LAYOUT_SERVICE_CONFIGURATION_NAME || 'default';
config.publicUrl = process.env.PUBLIC_URL || 'http://localhost:3000';
module.exports = config;